refactor(server): rewrite floorController and remove Geojson package
Can't use the @types/geojson package because it's not compatible with the tsoa package.
GenerateMetadataError: Unknown type: TupleType At: /node_modules/@types/geojson/index.d.ts:22:22.
This was caused by
'[number, number, number, number] | [number, number, number, number, number, number]'